parameters:
  vivait_delayed_event.queue.configuration.host: 'localhost'
  vivait_delayed_event.queue.configuration.port: 5672
  vivait_delayed_event.queue.configuration.user: 'guest'
  vivait_delayed_event.queue.configuration.password: 'guest'
  vivait_delayed_event.queue.configuration.vhost: '/'
  vivait_delayed_event.queue.configuration.insist: false
  vivait_delayed_event.queue.configuration.login_method: 'AMQPLAIN'
  vivait_delayed_event.queue.configuration.login_response: ~
  vivait_delayed_event.queue.configuration.locale: 'en_US'
  vivait_delayed_event.queue.configuration.connection_timeout: 3
  vivait_delayed_event.queue.configuration.read_write_timeout: 3
  vivait_delayed_event.queue.configuration.ssl_context: ~
  vivait_delayed_event.queue.configuration.keepalive: false
  vivait_delayed_event.queue.configuration.heartbeat: 0

services:
  vivait_delayed_event.queue:
    alias: vivait_delayed_event.queue.rabbitmq

  vivait_delayed_event.queue.rabbitmq.amqp:
    class: PhpAmqpLib\Connection\AMQPStreamConnection
    arguments:
      - '%vivait_delayed_event.queue.configuration.host%'
      - '%vivait_delayed_event.queue.configuration.port%'
      - '%vivait_delayed_event.queue.configuration.user%'
      - '%vivait_delayed_event.queue.configuration.password%'
      - '%vivait_delayed_event.queue.configuration.vhost%'
      - '%vivait_delayed_event.queue.configuration.insist%'
      - '%vivait_delayed_event.queue.configuration.login_method%'
      - '%vivait_delayed_event.queue.configuration.login_response%'
      - '%vivait_delayed_event.queue.configuration.locale%'
      - '%vivait_delayed_event.queue.configuration.connection_timeout%'
      - '%vivait_delayed_event.queue.configuration.read_write_timeout%'
      - '%vivait_delayed_event.queue.configuration.ssl_context%'
      - '%vivait_delayed_event.queue.configuration.keepalive%'
      - '%vivait_delayed_event.queue.configuration.heartbeat%'

  vivait_delayed_event.queue.rabbitmq:
    class: Vivait\DelayedEventBundle\Queue\RabbitMQ
    arguments:
      - @vivait_delayed_event.serializer
      - @vivait_delayed_event.queue.rabbitmq.amqp
